#!/bin/bash
#https://wiki.archlinux.org/

#mirrors
sed -i -e '1iServer = http://mirrors.163.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
echo -e "[archlinuxcn]\nServer = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/\$arch\n" >> /etc/pacman.conf
yes | pacman -Sy
yes | pacman -S archlinuxcn-keyring

#env
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "arch" > /etc/hostname
echo -e "127.0.0.1	localhost\n::1		localhost" > /etc/hosts

#user
echo "set root password"
passwd
echo "add general user"
read generaluser
useradd $generaluser
echo "set user password"
passwd $generaluser

#grub
yes | pacman -S grub
echo "set grub-install disk, example input /dev/sdb"
read diskn
grub-install --target=i386-pc $diskn
grub-mkconfig -o /boot/grub/grub.cfg

#network
yes | pacman -S networkmanager
systemctl enable NetworkManager
yes | pacman -S wpa_supplicant

#xorg
yes | pacman -S xorg-server
yes | pacman -S xorg-apps
yes | pacman -S xf86-video-intel

#kde
yes | pacman -S plasma-meta
#yes | pacman -S kde-applications-meta
yes | pacman -S sddm
systemctl enable sddm

#input method
yes | pacman -S fcitx-sogoupinyin
yes | pacman -S fcitx-im
yes | pacman -S wqy-bitmapfont
yes | pacman -S wqy-microhei
yes | pacman -S wqy-microhei-lite
yes | pacman -S wqy-zenhei
yes | pacman -S wqy-microhei-kr-patched

#most used software
yes | pacman -S htop
yes | pacman -S tmux
yes | pacman -S openssh
yes | pacman -S mlocate
yes | pacman -S latte-dock
yes | pacman -S spectacle
yes | pacman -S git
yes | pacman -S shadowsocks
yes | pacman -S python-pip
pip install web.py==0.40-dev1 -i https://pypi.tuna.tsinghua.edu.cn/simple
mkdir /root/.pip
echo -e "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple\n[install]\ntrusted-host=pypi.tuna.tsinghua.edu.cn" > /root/.pip/pip.conf
echo "SUBSYSTEM==“usb”,ATTR{idVendor}==“18d1”,MODE=“0666”" > /etc/udev/rules.d/51-android.rules

#dns
echo -e "# Generated by wzl\nsearch wr\nnameserver 8.8.8.8\nnameserver 223.5.5.5\nnameserver 219.141.140.10" > /etc/resolv.conf
chattr +i /etc/resolv.conf
